version: '3.4'

services:
  acabackendjavascript:
    image: acabackendjavascript
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3500:3500
